apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
