apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app_name }}
            - secretRef:
                name: {{ .Values.app_name }}
