app_name: shipments-api

replicaCount: 2

image:
  repository: 401413892014.dkr.ecr.us-east-1.amazonaws.com/routebox-shipments-api
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerPort: 3000

config:
  NODE_ENV: "staging"
  PORT: "3000"
  LOG_LEVEL: "info"
  LEGACY_EXPORT_ENABLED: "true"
  AWS_REGION: "us-east-1"
