apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-api
  labels:
    app: shipments-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipments-api
  template:
    metadata:
      labels:
        app: shipments-api
    spec:
      containers:
        - name: shipments-api
          image: 957117875370.dkr.ecr.us-east-1.amazonaws.com/routebox-shipments-api:aacf6dd
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: shipments-api
            - secretRef:
                name: shipments-api
