name: Build and Deploy

# triggers
on:
  push:
    branches:
      - staging
      - feature/*
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-deploy:
    # if staging branch => use staging environment  
    # otherwise => use dev environment,
    environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}
     
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: routebox-shipments-api
      # IMAGE_TAG: ${{ github.sha }}
    # defaults:
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.IAM_ROLE }}
        role-session-name: gha-session

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        # login to Tooling AWS account to push images to ECR
        registries: "957117875370"

    - name: Get short SHA
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" ./routebox-shipments-api

    - name: Push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}      
      run: |
        docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name ${{ vars.CLUSTER_NAME }}

    - name: Deploy to Kubernetes/EKS
      run: |
        helm upgrade --install shipments-api ./helm/shipments-api \
          --namespace app-${{ vars.STAGE }} --create-namespace \
          --set image.tag=${IMAGE_TAG} \
          --values ./helm/shipments-api/${{ vars.STAGE }}-values.yaml
